In [ ]:
#This code adds percentage changes to the code of absolute changes, and divides it in two separate csv tables.
import pandas as pd
import numpy as np

df20= pd.read_csv("df_new20.csv", index_col=0)
dfdelta= pd.read_csv("df_newdelta.csv", index_col="GeoName")

In [ ]:
# display(df20.head(2))
# display(dfdelta.head(2))

,GDP,CDPI,CPI,PCE,PersonalIncome,RPP,JobsNumber,year,population,Jobs/Population,CGDP,CPCE
GeoName,,,,,,,,,,,,
UNITED STATES,21354105.0,52357,59123,14225657.2,19600945.0,100.000,195262600,2020,331577720,0.588889,64401,42910
ALABAMA,235325.3,41829,45854,175833.9,230732.2,87.561,2670753,2020,5033094,0.530638,46755,34944

,GDP,CDPI,CPI,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP,CPCE
GeoName,,,,,,,,,,,
UNITED STATES,6366604.0,8934,10687,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,17903,13292
ALABAMA,69610.3,7116,8355,51641.1,46193.4,2.409,268600,84579,0.043715,12829,9585

In [ ]:
totdf = dfdelta[['GDP', 'PCE', 'PersonalIncome', 'RPP', 'JobsNumber',
       'population', 'Jobs/Population', 'CGDP','CDPI', 'CPI','CPCE']]

# totdf.index= dfdelta.index

In [ ]:
#Adding percentage changes:  (2023-2020)/(2020)
totdf["%Pop_Ch"] = totdf.loc[:,"population"]/df20.loc[:,"population"]
totdf["%PI_Ch"] = totdf.loc[:,"PersonalIncome"]/df20.loc[:,"PersonalIncome"]
totdf["%GDP_Ch"] = totdf.loc[:,"GDP"]/df20.loc[:,"GDP"]
totdf["%Jobs_Ch"] = totdf.loc[:,"JobsNumber"]/df20.loc[:,"JobsNumber"]
totdf["%PCE_Ch"] = totdf.loc[:,"PCE"]/df20.loc[:,"PCE"]

totdf["%CDPI_Ch"] = totdf.loc[:,"CDPI"]/df20.loc[:,"CDPI"]
totdf["%CPI_Ch"] = totdf.loc[:,"CPI"]/df20.loc[:,"CPI"]
totdf["%CGDP_Ch"] = totdf.loc[:,"CGDP"]/df20.loc[:,"CGDP"]
totdf["%CPCE_Ch"] = totdf.loc[:,"CPCE"]/df20.loc[:,"CPCE"]

<ipython-input-3-de4e2ead2ea1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%Pop_Ch"] = totdf.loc[:,"population"]/df20.loc[:,"population"]
<ipython-input-3-de4e2ead2ea1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%PI_Ch"] = totdf.loc[:,"PersonalIncome"]/df20.loc[:,"PersonalIncome"]
<ipython-input-3-de4e2ead2ea1>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%GDP_Ch"] = totdf.loc[:,"GDP"]/df20.loc[:,"GDP"]
<ipython-input-3-de4e2ead2ea1>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%Jobs_Ch"] = totdf.loc[:,"JobsNumber"]/df20.loc[:,"JobsNumber"]
<ipython-input-3-de4e2ead2ea1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%PCE_Ch"] = totdf.loc[:,"PCE"]/df20.loc[:,"PCE"]
<ipython-input-3-de4e2ead2ea1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%CDPI_Ch"] = totdf.loc[:,"CDPI"]/df20.loc[:,"CDPI"]
<ipython-input-3-de4e2ead2ea1>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%CPI_Ch"] = totdf.loc[:,"CPI"]/df20.loc[:,"CPI"]
<ipython-input-3-de4e2ead2ea1>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%CGDP_Ch"] = totdf.loc[:,"CGDP"]/df20.loc[:,"CGDP"]
<ipython-input-3-de4e2ead2ea1>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  totdf["%CPCE_Ch"] = totdf.loc[:,"CPCE"]/df20.loc[:,"CPCE"]

In [ ]:
totdf.head(5)

,GDP,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP,CDPI,CPI,CPCE,%Pop_Ch,%PI_Ch,%GDP_Ch,%Jobs_Ch,%PCE_Ch,%CDPI_Ch,%CPI_Ch,%CGDP_Ch,%CPCE_Ch
GeoName,,,,,,,,,,,,,,,,,,,,
UNITED STATES,6366604.0,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,17903,8934,10687,13292,0.015769,0.192813,0.298144,0.107812,0.323156,0.170636,0.180759,0.277993,0.309765
ALABAMA,69610.3,51641.1,46193.4,2.409,268600,84579,0.043715,12829,7116,8355,9585,0.016805,0.200204,0.295805,0.100571,0.293693,0.170121,0.182209,0.274388,0.274296
DELAWARE,20548.4,14788.1,13932.6,2.471,71024,44495,0.042900,16471,9799,11349,12582,0.044857,0.253095,0.265071,0.119945,0.330657,0.200029,0.204483,0.210759,0.279042
DISTRICT OF COLUMBIA,29841.6,15463.3,11678.9,-0.090,47309,16407,0.038017,38199,13218,16114,21935,0.024455,0.191941,0.203475,0.054625,0.328817,0.173192,0.177659,0.174747,0.312901
FLORIDA,458806.2,395674.4,332643.7,2.842,2037576,1312833,0.055195,16999,10634,12163,15483,0.060802,0.272484,0.401755,0.160200,0.409780,0.211252,0.215122,0.321403,0.346213

In [ ]:
list(totdf.columns)
totdelta = totdf.loc(axis=1)[['GDP','PCE','PersonalIncome','JobsNumber','population','Jobs/Population','CGDP','CDPI','CPI','CPCE']]
pctdelta = totdf.loc(axis=1)[['RPP','%Pop_Ch','%PI_Ch','%GDP_Ch','%Jobs_Ch','%PCE_Ch','%CDPI_Ch','%CPI_Ch','%CGDP_Ch','%CPCE_Ch']]

In [ ]:
# display(totdf.head(2))
# display(totdelta.head(2))
# display(pctdelta.head(2))

,GDP,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP,CDPI,CPI,%Pop_Ch,%PI_Ch,%GDP_Ch,%Jobs_Ch,%PCE_Ch,%CDPI_Ch,%CPI_Ch,%CGDP_Ch
GeoName,,,,,,,,,,,,,,,,,,
United States,6366604.0,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,17903,8934,10687,0.015769,0.192813,0.298144,0.107812,0.323156,0.170636,0.180759,0.277993
Alabama,69610.3,51641.1,46193.4,2.409,268600,84579,0.043715,12829,7116,8355,0.016805,0.200204,0.295805,0.100571,0.293693,0.170121,0.182209,0.274388

,GDP,PCE,PersonalIncome,JobsNumber,population,Jobs/Population,CGDP,CDPI,CPI
GeoName,,,,,,,,,
United States,6366604.0,4597111.6,3779324.0,21051600,5228511,0.053362,17903,8934,10687
Alabama,69610.3,51641.1,46193.4,268600,84579,0.043715,12829,7116,8355

,RPP,%Pop_Ch,%PI_Ch,%GDP_Ch,%Jobs_Ch,%PCE_Ch,%CDPI_Ch,%CPI_Ch,%CGDP_Ch
GeoName,,,,,,,,,
United States,0.000,0.015769,0.192813,0.298144,0.107812,0.323156,0.170636,0.180759,0.277993
Alabama,2.409,0.016805,0.200204,0.295805,0.100571,0.293693,0.170121,0.182209,0.274388

In [ ]:
from google.colab import files
totdf.to_csv("delta_merged.csv",index=True)
files.download('delta_merged.csv')

totdelta.to_csv("totdelta.csv",index=True)
files.download('totdelta.csv')

pctdelta.to_csv("pctdelta.csv",index=True)
files.download('pctdelta.csv')