In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving election_percentages_24.csv to election_percentages_24.csv

In [ ]:
df_newdelta = pd.read_csv('df_newdelta.csv') # upload file
df_newdelta=df_newdelta.set_index('GeoName')
df_newdelta

,GDP,CDPI,CPI,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP
GeoName,,,,,,,,,,
United States,6366604.0,8934,10687,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,0.017903
Alabama,69610.3,7116,8355,51641.1,46193.4,2.409,268600,84579,0.043715,0.012829
Delaware,20548.4,9799,11349,14788.1,13932.6,2.471,71024,44495,0.042900,0.016471
District of Columbia,29841.6,13218,16114,15463.3,11678.9,-0.090,47309,16407,0.038017,0.038199
Florida,458806.2,10634,12163,395674.4,332643.7,2.842,2037576,1312833,0.055195,0.016999
Georgia,191604.1,6780,8419,141982.6,108131.2,2.223,810606,331544,0.055601,0.015530
Hawaii,25379.6,7420,9177,19356.0,12256.7,-4.640,103426,-9865,0.075610,0.018008
Idaho,32859.0,8505,9776,26678.8,24932.1,0.406,139417,121707,0.034756,0.013729
Illinois,237673.3,8546,10661,169855.9,118960.0,-1.486,658574,-156829,0.059381,0.019634
Indiana,120869.5,8060,9497,80074.3,68948.9,0.418,362265,89634,0.045281,0.016841
Iowa,55422.4,9055,10154,32316.5,33412.6,-1.839,123412,27273,0.033006,0.016693
Alaska,16772.6,8611,9753,11067.3,7180.4,0.365,36420,3493,0.046662,0.022441
Kansas,51022.8,9584,11014,31680.6,32521.1,-2.299,119776,13328,0.037694,0.017015
Kentucky,61167.8,7098,8306,49230.6,38443.7,1.384,239220,42277,0.047478,0.012991
Louisiana,78772.3,7221,8709,47128.5,35906.7,-2.807,241199,-64230,0.060372,0.017880
Maine,21192.9,9267,10808,21023.7,16779.1,-0.789,76787,35075,0.039933,0.013818
Maryland,102151.9,8457,10507,76367.9,65360.4,-2.421,355603,39127,0.053508,0.016010
Massachusetts,143643.3,9892,13161,114539.8,92425.3,-0.859,451448,71970,0.057187,0.019464
Michigan,144142.5,7025,8346,109166.7,82011.0,-0.240,561972,10653,0.055167,0.014240
Minnesota,104415.5,9549,11229,74673.0,66105.1,0.668,289947,42313,0.045753,0.017662
Mississippi,34437.3,6430,7204,26781.4,20382.7,1.712,131148,-15364,0.047335,0.011907
Missouri,94829.3,8910,10459,74698.5,66980.2,-0.395,288438,53294,0.041314,0.014808
Montana,20295.7,9353,11501,16731.7,15467.0,-1.729,73915,44072,0.040850,0.016043
Nebraska,46135.6,13053,14598,23887.9,29737.8,-2.434,92586,24477,0.038387,0.022361
Nevada,69682.5,9437,11562,45695.8,41214.6,-0.208,351691,97396,0.092199,0.019965
New Hampshire,25573.1,9043,11407,21559.1,17569.8,0.074,86838,23443,0.051520,0.017164
New Jersey,175112.9,9603,11670,138936.5,109723.2,-1.829,716989,106848,0.069906,0.017894
New Mexico,34353.2,7001,8857,23079.8,18536.1,-1.421,97113,2558,0.045175,0.016138
New York,398639.8,8643,11927,285323.0,195871.9,-2.492,1301857,-367804,0.076962,0.021841
North Carolina,187419.9,8689,10081,145112.5,128983.6,2.794,718672,431537,0.043070,0.014944
North Dakota,20474.8,9902,11673,8610.7,9414.8,-3.242,37918,9484,0.039417,0.025092
Ohio,192150.5,7293,8653,127013.4,101335.0,-0.120,543230,25129,0.044709,0.016126
Arizona,133810.5,9375,10501,108765.2,90767.7,1.898,464218,285892,0.041256,0.015835
Oklahoma,64173.2,9396,10523,41934.7,47090.6,-1.348,189839,98467,0.032872,0.014615
Oregon,67306.4,8870,11261,55333.3,47008.8,1.475,199822,9874,0.045613,0.015686
Pennsylvania,199360.0,6969,8696,164428.2,110690.3,-0.187,682601,21578,0.051491,0.015215
Rhode Island,15449.0,6885,8307,13937.1,9076.1,-0.355,65785,6899,0.056108,0.013647
South Carolina,77989.9,7260,8562,68546.0,57784.1,2.303,325220,255581,0.034253,0.012170
South Dakota,17779.5,11814,13037,11213.5,13855.8,-3.231,51022,30357,0.033000,0.017267
Tennessee,131468.4,9033,10270,89683.1,83599.1,2.016,493767,220400,0.050741,0.016649
Texas,781722.5,10128,11447,418092.8,418715.6,-1.599,2474957,1488320,0.051229,0.022455
Utah,75681.2,10371,12433,49012.6,49410.5,-0.260,280624,159145,0.051443,0.019085
Arkansas,42408.0,9313,10532,30154.1,34823.4,-1.660,149752,54917,0.039061,0.013008
Vermont,9118.9,7158,8798,7772.1,5959.2,-5.497,33147,5731,0.045474,0.013584
Virginia,154430.1,10678,12438,114902.4,113226.8,-0.261,495365,97070,0.049990,0.016953
Washington,187731.6,10783,13287,115845.3,109786.8,0.693,446566,130111,0.047330,0.022564
West Virginia,24720.9,6845,7957,17134.7,13118.8,2.439,62839,-21151,0.041100,0.014479
Wisconsin,85174.9,8211,9541,72085.6,57187.1,0.432,274492,33030,0.042904,0.014038
Wyoming,15280.9,14489,16964,7603.7,10324.5,-0.983,41654,7386,0.062424,0.025316
California,793623.8,9087,11157,638016.0,397032.4,0.640,2264723,-323265,0.062607,0.020888
Colorado,132884.6,13198,15375,100600.0,96343.7,-2.384,420970,114210,0.058557,0.021191
Connecticut,67882.5,10831,13116,51136.8,50483.8,-1.402,199261,63105,0.043967,0.017288

In [ ]:
df_election_24= pd.read_csv('election_percentages_24.csv')
df_election_24=df_election_24.rename(columns={'Unnamed: 0':'GeoName'}) # rename column
df_election_24=df_election_24.set_index('GeoName') #set index
df_election_24

                      REPUBLICAN  DEMOCRAT
GeoName
United States              49.81     48.33
Alabama                    64.60     34.10
Alaska                     54.50     41.40
Arizona                    52.20     46.70
Arkansas                   64.20     33.60
California                 38.30     58.50
Colorado                   43.10     54.10
Connecticut                41.90     56.40
Delaware                   41.80     56.50
District of Columbia        6.50     90.30
Florida                    56.10     43.00
Georgia                    50.70     48.50
Hawaii                     37.50     60.60
Idaho                      66.90     30.40
Illinois                   43.50     54.40
Indiana                    58.80     39.40
Iowa                       55.70     42.50
Kansas                     57.20     41.00
Kentucky                   64.50     33.90
Louisiana                  60.20     38.20
Maine                      45.50     52.40
Maryland                   34.10     62.60
Massachusetts              36.00     61.20
Michigan                   49.70     48.30
Minnesota                  46.70     50.90
Mississippi                60.90     38.00
Missouri                   58.50     40.10
Montana                    58.40     38.50
Nebraska                   59.30     38.90
Nevada                     50.60     47.50
New Hampshire              47.90     50.70
New Jersey                 46.10     52.00
New Mexico                 45.90     51.90
New York                   43.30     55.90
North Carolina             50.90     47.70
North Dakota               67.00     30.50
Ohio                       55.10     43.90
Oklahoma                   66.20     31.90
Oregon                     41.00     55.30
Pennsylvania               50.40     48.70
Rhode Island               41.80     55.50
South Carolina             58.20     40.40
South Dakota               63.40     34.20
Tennessee                  64.20     34.50
Texas                      56.10     42.50
Utah                       59.40     37.80
Vermont                    32.00     63.20
Virginia                   46.10     51.80
Washington                 39.00     57.20
West Virginia              70.00     28.10
Wisconsin                  49.60     48.70
Wyoming                    71.60     25.80

In [ ]:
df_merge = pd.merge(df_newdelta,df_election_24,on='GeoName') # merge two data
df_merge

,GDP,CDPI,CPI,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP,REPUBLICAN,DEMOCRAT
GeoName,,,,,,,,,,,,
United States,6366604.0,8934,10687,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,0.017903,49.81,48.33
Alabama,69610.3,7116,8355,51641.1,46193.4,2.409,268600,84579,0.043715,0.012829,64.60,34.10
Delaware,20548.4,9799,11349,14788.1,13932.6,2.471,71024,44495,0.042900,0.016471,41.80,56.50
District of Columbia,29841.6,13218,16114,15463.3,11678.9,-0.090,47309,16407,0.038017,0.038199,6.50,90.30
Florida,458806.2,10634,12163,395674.4,332643.7,2.842,2037576,1312833,0.055195,0.016999,56.10,43.00
Georgia,191604.1,6780,8419,141982.6,108131.2,2.223,810606,331544,0.055601,0.015530,50.70,48.50
Hawaii,25379.6,7420,9177,19356.0,12256.7,-4.640,103426,-9865,0.075610,0.018008,37.50,60.60
Idaho,32859.0,8505,9776,26678.8,24932.1,0.406,139417,121707,0.034756,0.013729,66.90,30.40
Illinois,237673.3,8546,10661,169855.9,118960.0,-1.486,658574,-156829,0.059381,0.019634,43.50,54.40
Indiana,120869.5,8060,9497,80074.3,68948.9,0.418,362265,89634,0.045281,0.016841,58.80,39.40
Iowa,55422.4,9055,10154,32316.5,33412.6,-1.839,123412,27273,0.033006,0.016693,55.70,42.50
Alaska,16772.6,8611,9753,11067.3,7180.4,0.365,36420,3493,0.046662,0.022441,54.50,41.40
Kansas,51022.8,9584,11014,31680.6,32521.1,-2.299,119776,13328,0.037694,0.017015,57.20,41.00
Kentucky,61167.8,7098,8306,49230.6,38443.7,1.384,239220,42277,0.047478,0.012991,64.50,33.90
Louisiana,78772.3,7221,8709,47128.5,35906.7,-2.807,241199,-64230,0.060372,0.017880,60.20,38.20
Maine,21192.9,9267,10808,21023.7,16779.1,-0.789,76787,35075,0.039933,0.013818,45.50,52.40
Maryland,102151.9,8457,10507,76367.9,65360.4,-2.421,355603,39127,0.053508,0.016010,34.10,62.60
Massachusetts,143643.3,9892,13161,114539.8,92425.3,-0.859,451448,71970,0.057187,0.019464,36.00,61.20
Michigan,144142.5,7025,8346,109166.7,82011.0,-0.240,561972,10653,0.055167,0.014240,49.70,48.30
Minnesota,104415.5,9549,11229,74673.0,66105.1,0.668,289947,42313,0.045753,0.017662,46.70,50.90
Mississippi,34437.3,6430,7204,26781.4,20382.7,1.712,131148,-15364,0.047335,0.011907,60.90,38.00
Missouri,94829.3,8910,10459,74698.5,66980.2,-0.395,288438,53294,0.041314,0.014808,58.50,40.10
Montana,20295.7,9353,11501,16731.7,15467.0,-1.729,73915,44072,0.040850,0.016043,58.40,38.50
Nebraska,46135.6,13053,14598,23887.9,29737.8,-2.434,92586,24477,0.038387,0.022361,59.30,38.90
Nevada,69682.5,9437,11562,45695.8,41214.6,-0.208,351691,97396,0.092199,0.019965,50.60,47.50
New Hampshire,25573.1,9043,11407,21559.1,17569.8,0.074,86838,23443,0.051520,0.017164,47.90,50.70
New Jersey,175112.9,9603,11670,138936.5,109723.2,-1.829,716989,106848,0.069906,0.017894,46.10,52.00
New Mexico,34353.2,7001,8857,23079.8,18536.1,-1.421,97113,2558,0.045175,0.016138,45.90,51.90
New York,398639.8,8643,11927,285323.0,195871.9,-2.492,1301857,-367804,0.076962,0.021841,43.30,55.90
North Carolina,187419.9,8689,10081,145112.5,128983.6,2.794,718672,431537,0.043070,0.014944,50.90,47.70
North Dakota,20474.8,9902,11673,8610.7,9414.8,-3.242,37918,9484,0.039417,0.025092,67.00,30.50
Ohio,192150.5,7293,8653,127013.4,101335.0,-0.120,543230,25129,0.044709,0.016126,55.10,43.90
Arizona,133810.5,9375,10501,108765.2,90767.7,1.898,464218,285892,0.041256,0.015835,52.20,46.70
Oklahoma,64173.2,9396,10523,41934.7,47090.6,-1.348,189839,98467,0.032872,0.014615,66.20,31.90
Oregon,67306.4,8870,11261,55333.3,47008.8,1.475,199822,9874,0.045613,0.015686,41.00,55.30
Pennsylvania,199360.0,6969,8696,164428.2,110690.3,-0.187,682601,21578,0.051491,0.015215,50.40,48.70
Rhode Island,15449.0,6885,8307,13937.1,9076.1,-0.355,65785,6899,0.056108,0.013647,41.80,55.50
South Carolina,77989.9,7260,8562,68546.0,57784.1,2.303,325220,255581,0.034253,0.012170,58.20,40.40
South Dakota,17779.5,11814,13037,11213.5,13855.8,-3.231,51022,30357,0.033000,0.017267,63.40,34.20
Tennessee,131468.4,9033,10270,89683.1,83599.1,2.016,493767,220400,0.050741,0.016649,64.20,34.50
Texas,781722.5,10128,11447,418092.8,418715.6,-1.599,2474957,1488320,0.051229,0.022455,56.10,42.50
Utah,75681.2,10371,12433,49012.6,49410.5,-0.260,280624,159145,0.051443,0.019085,59.40,37.80
Arkansas,42408.0,9313,10532,30154.1,34823.4,-1.660,149752,54917,0.039061,0.013008,64.20,33.60
Vermont,9118.9,7158,8798,7772.1,5959.2,-5.497,33147,5731,0.045474,0.013584,32.00,63.20
Virginia,154430.1,10678,12438,114902.4,113226.8,-0.261,495365,97070,0.049990,0.016953,46.10,51.80
Washington,187731.6,10783,13287,115845.3,109786.8,0.693,446566,130111,0.047330,0.022564,39.00,57.20
West Virginia,24720.9,6845,7957,17134.7,13118.8,2.439,62839,-21151,0.041100,0.014479,70.00,28.10
Wisconsin,85174.9,8211,9541,72085.6,57187.1,0.432,274492,33030,0.042904,0.014038,49.60,48.70
Wyoming,15280.9,14489,16964,7603.7,10324.5,-0.983,41654,7386,0.062424,0.025316,71.60,25.80
California,793623.8,9087,11157,638016.0,397032.4,0.640,2264723,-323265,0.062607,0.020888,38.30,58.50
Colorado,132884.6,13198,15375,100600.0,96343.7,-2.384,420970,114210,0.058557,0.021191,43.10,54.10
Connecticut,67882.5,10831,13116,51136.8,50483.8,-1.402,199261,63105,0.043967,0.017288,41.90,56.40

In [ ]:
df_merge['Result']=df_merge.apply(lambda x:'REPUBLICAN' if x['REPUBLICAN']>x['DEMOCRAT'] else 'DEMOCRAT',axis=1) # find the win party

In [ ]:
df_merge

,GDP,CDPI,CPI,PCE,PersonalIncome,RPP,JobsNumber,population,Jobs/Population,CGDP,REPUBLICAN,DEMOCRAT,Result
GeoName,,,,,,,,,,,,,
United States,6366604.0,8934,10687,4597111.6,3779324.0,0.000,21051600,5228511,0.053362,0.017903,49.81,48.33,REPUBLICAN
Alabama,69610.3,7116,8355,51641.1,46193.4,2.409,268600,84579,0.043715,0.012829,64.60,34.10,REPUBLICAN
Delaware,20548.4,9799,11349,14788.1,13932.6,2.471,71024,44495,0.042900,0.016471,41.80,56.50,DEMOCRAT
District of Columbia,29841.6,13218,16114,15463.3,11678.9,-0.090,47309,16407,0.038017,0.038199,6.50,90.30,DEMOCRAT
Florida,458806.2,10634,12163,395674.4,332643.7,2.842,2037576,1312833,0.055195,0.016999,56.10,43.00,REPUBLICAN
Georgia,191604.1,6780,8419,141982.6,108131.2,2.223,810606,331544,0.055601,0.015530,50.70,48.50,REPUBLICAN
Hawaii,25379.6,7420,9177,19356.0,12256.7,-4.640,103426,-9865,0.075610,0.018008,37.50,60.60,DEMOCRAT
Idaho,32859.0,8505,9776,26678.8,24932.1,0.406,139417,121707,0.034756,0.013729,66.90,30.40,REPUBLICAN
Illinois,237673.3,8546,10661,169855.9,118960.0,-1.486,658574,-156829,0.059381,0.019634,43.50,54.40,DEMOCRAT
Indiana,120869.5,8060,9497,80074.3,68948.9,0.418,362265,89634,0.045281,0.016841,58.80,39.40,REPUBLICAN
Iowa,55422.4,9055,10154,32316.5,33412.6,-1.839,123412,27273,0.033006,0.016693,55.70,42.50,REPUBLICAN
Alaska,16772.6,8611,9753,11067.3,7180.4,0.365,36420,3493,0.046662,0.022441,54.50,41.40,REPUBLICAN
Kansas,51022.8,9584,11014,31680.6,32521.1,-2.299,119776,13328,0.037694,0.017015,57.20,41.00,REPUBLICAN
Kentucky,61167.8,7098,8306,49230.6,38443.7,1.384,239220,42277,0.047478,0.012991,64.50,33.90,REPUBLICAN
Louisiana,78772.3,7221,8709,47128.5,35906.7,-2.807,241199,-64230,0.060372,0.017880,60.20,38.20,REPUBLICAN
Maine,21192.9,9267,10808,21023.7,16779.1,-0.789,76787,35075,0.039933,0.013818,45.50,52.40,DEMOCRAT
Maryland,102151.9,8457,10507,76367.9,65360.4,-2.421,355603,39127,0.053508,0.016010,34.10,62.60,DEMOCRAT
Massachusetts,143643.3,9892,13161,114539.8,92425.3,-0.859,451448,71970,0.057187,0.019464,36.00,61.20,DEMOCRAT
Michigan,144142.5,7025,8346,109166.7,82011.0,-0.240,561972,10653,0.055167,0.014240,49.70,48.30,REPUBLICAN
Minnesota,104415.5,9549,11229,74673.0,66105.1,0.668,289947,42313,0.045753,0.017662,46.70,50.90,DEMOCRAT
Mississippi,34437.3,6430,7204,26781.4,20382.7,1.712,131148,-15364,0.047335,0.011907,60.90,38.00,REPUBLICAN
Missouri,94829.3,8910,10459,74698.5,66980.2,-0.395,288438,53294,0.041314,0.014808,58.50,40.10,REPUBLICAN
Montana,20295.7,9353,11501,16731.7,15467.0,-1.729,73915,44072,0.040850,0.016043,58.40,38.50,REPUBLICAN
Nebraska,46135.6,13053,14598,23887.9,29737.8,-2.434,92586,24477,0.038387,0.022361,59.30,38.90,REPUBLICAN
Nevada,69682.5,9437,11562,45695.8,41214.6,-0.208,351691,97396,0.092199,0.019965,50.60,47.50,REPUBLICAN
New Hampshire,25573.1,9043,11407,21559.1,17569.8,0.074,86838,23443,0.051520,0.017164,47.90,50.70,DEMOCRAT
New Jersey,175112.9,9603,11670,138936.5,109723.2,-1.829,716989,106848,0.069906,0.017894,46.10,52.00,DEMOCRAT
New Mexico,34353.2,7001,8857,23079.8,18536.1,-1.421,97113,2558,0.045175,0.016138,45.90,51.90,DEMOCRAT
New York,398639.8,8643,11927,285323.0,195871.9,-2.492,1301857,-367804,0.076962,0.021841,43.30,55.90,DEMOCRAT
North Carolina,187419.9,8689,10081,145112.5,128983.6,2.794,718672,431537,0.043070,0.014944,50.90,47.70,REPUBLICAN
North Dakota,20474.8,9902,11673,8610.7,9414.8,-3.242,37918,9484,0.039417,0.025092,67.00,30.50,REPUBLICAN
Ohio,192150.5,7293,8653,127013.4,101335.0,-0.120,543230,25129,0.044709,0.016126,55.10,43.90,REPUBLICAN
Arizona,133810.5,9375,10501,108765.2,90767.7,1.898,464218,285892,0.041256,0.015835,52.20,46.70,REPUBLICAN
Oklahoma,64173.2,9396,10523,41934.7,47090.6,-1.348,189839,98467,0.032872,0.014615,66.20,31.90,REPUBLICAN
Oregon,67306.4,8870,11261,55333.3,47008.8,1.475,199822,9874,0.045613,0.015686,41.00,55.30,DEMOCRAT
Pennsylvania,199360.0,6969,8696,164428.2,110690.3,-0.187,682601,21578,0.051491,0.015215,50.40,48.70,REPUBLICAN
Rhode Island,15449.0,6885,8307,13937.1,9076.1,-0.355,65785,6899,0.056108,0.013647,41.80,55.50,DEMOCRAT
South Carolina,77989.9,7260,8562,68546.0,57784.1,2.303,325220,255581,0.034253,0.012170,58.20,40.40,REPUBLICAN
South Dakota,17779.5,11814,13037,11213.5,13855.8,-3.231,51022,30357,0.033000,0.017267,63.40,34.20,REPUBLICAN
Tennessee,131468.4,9033,10270,89683.1,83599.1,2.016,493767,220400,0.050741,0.016649,64.20,34.50,REPUBLICAN
Texas,781722.5,10128,11447,418092.8,418715.6,-1.599,2474957,1488320,0.051229,0.022455,56.10,42.50,REPUBLICAN
Utah,75681.2,10371,12433,49012.6,49410.5,-0.260,280624,159145,0.051443,0.019085,59.40,37.80,REPUBLICAN
Arkansas,42408.0,9313,10532,30154.1,34823.4,-1.660,149752,54917,0.039061,0.013008,64.20,33.60,REPUBLICAN
Vermont,9118.9,7158,8798,7772.1,5959.2,-5.497,33147,5731,0.045474,0.013584,32.00,63.20,DEMOCRAT
Virginia,154430.1,10678,12438,114902.4,113226.8,-0.261,495365,97070,0.049990,0.016953,46.10,51.80,DEMOCRAT
Washington,187731.6,10783,13287,115845.3,109786.8,0.693,446566,130111,0.047330,0.022564,39.00,57.20,DEMOCRAT
West Virginia,24720.9,6845,7957,17134.7,13118.8,2.439,62839,-21151,0.041100,0.014479,70.00,28.10,REPUBLICAN
Wisconsin,85174.9,8211,9541,72085.6,57187.1,0.432,274492,33030,0.042904,0.014038,49.60,48.70,REPUBLICAN
Wyoming,15280.9,14489,16964,7603.7,10324.5,-0.983,41654,7386,0.062424,0.025316,71.60,25.80,REPUBLICAN
California,793623.8,9087,11157,638016.0,397032.4,0.640,2264723,-323265,0.062607,0.020888,38.30,58.50,DEMOCRAT
Colorado,132884.6,13198,15375,100600.0,96343.7,-2.384,420970,114210,0.058557,0.021191,43.10,54.10,DEMOCRAT
Connecticut,67882.5,10831,13116,51136.8,50483.8,-1.402,199261,63105,0.043967,0.017288,41.90,56.40,DEMOCRAT

In [ ]:
df_merge.to_csv('df_merge.csv',index=True)
files.download('df_merge.csv') # download dataframe